In [1]:
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_rows', None)  # Show all rows
df = pd.read_csv('./all_holdings.csv')

df.head(25)

,fund_name,filing_date,quarter,stocksymbol,cl,value($000),shares,change,pct_change,inferred_transaction_type
0,AKRE CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,AAPL,COM,51069,91029.0,NaN,NaN,new
1,AKRE CAPITAL MANAGEMENT LLC,5/13/2014,Q1 2014,AAPL,COM,48859,91029.0,0.0,0.000000,hold
2,AKRE CAPITAL MANAGEMENT LLC,8/13/2014,Q2 2014,AAPL,COM,59219,637238.0,546209.0,6.000384,buy
3,AKRE CAPITAL MANAGEMENT LLC,11/13/2014,Q3 2014,AAPL,COM,64212,637338.0,100.0,0.000157,buy
4,AKRE CAPITAL MANAGEMENT LLC,5/11/2020,Q1 2020,ADBE,COM,362794,1140000.0,NaN,NaN,new
5,AKRE CAPITAL MANAGEMENT LLC,8/11/2020,Q2 2020,ADBE,COM,496253,1140000.0,0.0,0.000000,hold
6,AKRE CAPITAL MANAGEMENT LLC,11/13/2020,Q3 2020,ADBE,COM,559090,1140000.0,0.0,0.000000,hold
7,AKRE CAPITAL MANAGEMENT LLC,2/10/2021,Q4 2020,ADBE,COM,570137,1140000.0,0.0,0.000000,hold
8,AKRE CAPITAL MANAGEMENT LLC,7/9/2021,Q1 2021,ADBE,COM,727254,1529870.0,389870.0,0.341991,buy
9,AKRE CAPITAL MANAGEMENT LLC,8/13/2021,Q2 2021,ADBE,COM,896082,1530090.0,220.0,0.000144,buy
10,AKRE CAPITAL MANAGEMENT LLC,11/12/2021,Q3 2021,ADBE,COM,880843,1529985.0,-105.0,-0.000069,sell
11,AKRE CAPITAL MANAGEMENT LLC,2/11/2022,Q4 2021,ADBE,COM,867653,1530090.0,105.0,0.000069,buy
12,AKRE CAPITAL MANAGEMENT LLC,5/13/2022,Q1 2022,ADBE,COM,713998,1567090.0,37000.0,0.024182,buy
13,AKRE CAPITAL MANAGEMENT LLC,8/11/2022,Q2 2022,ADBE,COM,607804,1660395.0,93305.0,0.059540,buy
14,AKRE CAPITAL MANAGEMENT LLC,11/14/2022,Q3 2022,ADBE,COM,458454,1665895.0,5500.0,0.003312,buy
15,AKRE CAPITAL MANAGEMENT LLC,2/13/2023,Q4 2022,ADBE,COM,417148,1239558.0,-426337.0,-0.255921,sell
16,AKRE CAPITAL MANAGEMENT LLC,5/12/2023,Q1 2023,ADBE,COM,462089,1199081.0,-40477.0,-0.032654,sell
17,AKRE CAPITAL MANAGEMENT LLC,8/11/2023,Q2 2023,ADBE,COM,520324,1064081.0,-135000.0,-0.112586,sell
18,AKRE CAPITAL MANAGEMENT LLC,8/14/2015,Q2 2015,ALRM,COM,6152,400000.0,NaN,NaN,new
19,AKRE CAPITAL MANAGEMENT LLC,11/12/2015,Q3 2015,ALRM,COM,4664,400000.0,0.0,0.000000,hold
20,AKRE CAPITAL MANAGEMENT LLC,2/12/2016,Q4 2015,ALRM,COM,6672,400000.0,0.0,0.000000,hold
21,AKRE CAPITAL MANAGEMENT LLC,5/13/2016,Q1 2016,ALRM,COM,9480,400000.0,0.0,0.000000,hold
22,AKRE CAPITAL MANAGEMENT LLC,8/18/2017,Q2 2016,ALRM,COM,10252,400000.0,0.0,0.000000,hold
23,AKRE CAPITAL MANAGEMENT LLC,11/15/2016,Q3 2016,ALRM,COM,11544,400000.0,0.0,0.000000,hold
24,AKRE CAPITAL MANAGEMENT LLC,5/9/2017,Q4 2016,ALRM,COM,11132,400000.0,0.0,0.000000,hold

In [2]:
# Verificar valores nulos
df.isna().sum()

fund_name                         0
filing_date                       0
quarter                           0
stocksymbol                   33779
cl                                0
value($000)                       0
shares                          326
change                       120671
pct_change                   120653
inferred_transaction_type         0
dtype: int64

In [3]:
# Verificar muestra de filas donde stocksymbol es nulo
df[df['stocksymbol'].isna()].head(25)

,fund_name,filing_date,quarter,stocksymbol,cl,value($000),shares,change,pct_change,inferred_transaction_type
1560,APPALOOSA LP,8/14/2017,Q2 2017,NaN,COM,9974,189799.0,NaN,NaN,new
1561,APPALOOSA LP,11/14/2017,Q3 2017,NaN,COM,8252,169799.0,NaN,NaN,new
1562,APPALOOSA LP,5/15/2020,Q1 2020,NaN,COM,135817,5530000.0,NaN,NaN,new
1563,APPALOOSA LP,5/15/2020,Q1 2020,NaN,COM,54996,6380000.0,NaN,NaN,new
1564,APPALOOSA LP,8/14/2020,Q2 2020,NaN,COM,165335,5550000.0,NaN,NaN,new
1565,APPALOOSA LP,11/16/2020,Q3 2020,NaN,COM,207370,4660000.0,NaN,NaN,new
1566,APPALOOSA LP,2/16/2021,Q4 2020,NaN,COM,257213,4750000.0,NaN,NaN,new
1567,APPALOOSA LP,5/17/2021,Q1 2021,NaN,COM,168620,2650000.0,NaN,NaN,new
1568,APPALOOSA LP,8/16/2021,Q2 2021,NaN,COM,89453,1300000.0,NaN,NaN,new
1569,APPALOOSA LP,11/15/2021,Q3 2021,NaN,COM,74582,1235000.0,NaN,NaN,new
76237,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,106669,3337584.0,NaN,NaN,new
76238,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,103022,2087580.0,NaN,NaN,new
76239,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,42368,960082.0,NaN,NaN,new
76240,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,39844,1453627.0,NaN,NaN,new
76241,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,37499,626543.0,NaN,NaN,new
76242,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,23639,2329000.0,NaN,NaN,new
76243,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,22919,2375000.0,NaN,NaN,new
76244,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,17285,1782000.0,NaN,NaN,new
76245,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,15716,938297.0,NaN,NaN,new
76246,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,14944,236267.0,NaN,NaN,new
76247,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,14791,1477575.0,NaN,NaN,new
76248,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,14728,1390000.0,NaN,NaN,new
76249,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,11246,560339.0,NaN,NaN,new
76250,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,10848,151195.0,NaN,NaN,new
76251,AQR CAPITAL MANAGEMENT LLC,2/14/2014,Q4 2013,NaN,COM,10427,370542.0,NaN,NaN,new

In [4]:
# Parsear filing_date a valor de tipo fecha
df["filing_date"] = pd.to_datetime(df["filing_date"], dayfirst=True, errors="coerce")
# Parsear value($000), shares, change y pct_change a valores numéricos
for col in ["value($000)","shares","change","pct_change"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")
# Verificar lo anterior
df.dtypes

C:\Users\Santiago\AppData\Local\Temp\ipykernel_47032\3228048278.py:2: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["filing_date"] = pd.to_datetime(df["filing_date"], dayfirst=True, errors="coerce")

fund_name                            object
filing_date                  datetime64[ns]
quarter                              object
stocksymbol                          object
cl                                   object
value($000)                           int64
shares                              float64
change                              float64
pct_change                          float64
inferred_transaction_type            object
dtype: object

In [5]:
# Verificar valores extremos (outliers) por quarter.
df["quarter"].value_counts().sort_index()

quarter
Q1 2014    28169
Q1 2015    29409
Q1 2016    29460
Q1 2017    29602
Q1 2018    30754
Q1 2019    32466
Q1 2020    33707
Q1 2021    43568
Q1 2022    45911
Q1 2023    46893
Q1 2024    44886
Q1 2025       24
Q2 2014    29355
Q2 2015    30172
Q2 2016    28938
Q2 2017    29516
Q2 2018    31409
Q2 2019    44919
Q2 2020    34582
Q2 2021    45071
Q2 2022    45875
Q2 2023    45926
Q2 2024    44011
Q3 2014    28818
Q3 2015    29412
Q3 2016    28463
Q3 2017    30449
Q3 2018    30826
Q3 2019    34215
Q3 2020    35243
Q3 2021    38992
Q3 2022    45960
Q3 2023    45707
Q3 2024    41290
Q4 2013    28247
Q4 2014    29322
Q4 2015    29749
Q4 2016    29569
Q4 2017    31227
Q4 2018    35324
Q4 2019    38712
Q4 2020    42573
Q4 2021    53443
Q4 2022    41813
Q4 2023    45146
Q4 2024    41299
Name: count, dtype: int64

In [6]:
# Verificar proporciones de tipos de transacción
df["inferred_transaction_type"].value_counts(normalize=True)

inferred_transaction_type
buy     0.450694
sell    0.432578
new     0.073561
hold    0.043168
Name: proportion, dtype: float64

In [7]:
# Verificar número de trimestres scrapeados por cada fondo 
df.groupby("fund_name")["quarter"].nunique().sort_values()

fund_name
Thiel Macro LLC                                  7
Saber Capital Managment, LLC                     8
HAYMAN CAPITAL MANAGEMENT, L.P.                 12
CITADEL ADVISORS LLC                            15
XTX Topco Ltd                                   16
XXEC, Inc.                                      19
GOLDMAN SACHS GROUP INC                         20
Elliott Investment Management L.P.              20
Rokos Capital Management LLP                    21
Himalaya Capital Management LLC                 21
Ensign Peak Advisors, Inc                       21
Atreides Management, LP                         21
ShawSpring Partners LLC                         23
D1 Capital Partners L.P.                        25
HHLR ADVISORS, LTD.                             25
COOPERMAN LEON G                                27
TUDOR INVESTMENT CORP ET AL                     29
Scion Asset Management, LLC                     29
Chanos & Co LP                                  29
Melvin Capital Management LP                    30
STATE STREET CORP                               31
TPG Group Holdings (SBS) Advisors, Inc.         32
Stockbridge Partners LLC                        33
ARK Investment Management LLC                   33
SPRUCE HOUSE INVESTMENT MANAGEMENT LLC          35
APPALOOSA LP                                    36
Abdiel Capital Advisors, LP                     37
TCI FUND MANAGEMENT LTD                         39
JANA PARTNERS LLC                               39
RA CAPITAL MANAGEMENT, L.P.                     40
Dragoneer Investment Group, LLC                 41
KING STREET CAPITAL MANAGEMENT, L.P.            41
GREENLIGHT CAPITAL INC                          41
Marathon Partners Equity Management, LLC        42
Point72 Asset Management, L.P.                  43
BlackRock Inc.                                  43
Virtu Financial LLC                             44
YALE UNIVERSITY                                 44
D. E. Shaw & Co., Inc.                          45
Duquesne Family Office LLC                      45
AKRE CAPITAL MANAGEMENT LLC                     45
GLENVIEW CAPITAL MANAGEMENT, LLC                45
GATES FOUNDATION TRUST                          45
GEODE CAPITAL MANAGEMENT, LLC                   45
FARALLON CAPITAL MANAGEMENT LLC                 45
Balyasny Asset Management L.P.                  45
Blackstone Inc.                                 45
Bridgewater Associates, LP                      45
SOROS FUND MANAGEMENT LLC                       45
OAKTREE CAPITAL MANAGEMENT LP                   45
MILLER VALUE PARTNERS, LLC                      45
Matrix Capital Management Company, LP           45
MILLENNIUM MANAGEMENT LLC                       45
LONE PINE CAPITAL LLC                           45
ICAHN CARL C                                    45
Fundsmith LLP                                   45
COATUE MANAGEMENT LLC                           45
Carlyle Group Inc.                              45
BAUPOST GROUP LLC/MA                            45
BNP PARIBAS ASSET MANAGEMENT Holding S.A.       45
Berkshire Hathaway Inc                          45
BAILLIE GIFFORD & CO                            45
AQR CAPITAL MANAGEMENT LLC                      45
Altimeter Capital Management, LP                45
MOORE CAPITAL MANAGEMENT, LP                    45
Senvest Management, LLC                         45
SUSQUEHANNA INTERNATIONAL GROUP, LLP            45
Saba Capital Management, L.P.                   45
PAULSON & CO. INC.                              45
RENAISSANCE TECHNOLOGIES LLC                    45
SANDS CAPITAL MANAGEMENT, LLC                   45
Pershing Square Capital Management, L.P.        45
Whale Rock Capital Management LLC               45
Third Point LLC                                 45
TIGER GLOBAL MANAGEMENT LLC                     45
TWO SIGMA INVESTMENTS, LP                       45
VANGUARD GROUP INC                              45
VIKING GLOBAL INVESTORS LP                      45
York Capital Management Global Advisors, LLC    45
DAILY JOURNAL CORP                              46
Name: quarter, dtype: int64

In [8]:
# Verificación del filtro correctamente aplicado según la tarea.
non_com = df[df["cl"] != "COM"]
non_com["cl"].value_counts()

cl
COMMON STOCK    72984
Name: count, dtype: int64